# Generated by Django 4.2.3 on 2023-07-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='phone_number',
        ),
    ]
